import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Link from "next/link";
import HelloPage from "./hello";
import axios from "axios";
import { GetStaticProps, NextPage } from "next";
import { Character, CharacterWrapper, GetCharacterResults } from "../types";
import ImageLoader from "../imageLoader";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ characters }: CharacterWrapper) {
    return (
        // <div className={styles.main}>
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {characters.map((character) => {
                return (
                    <div key={character.id}>
                        <Link href={`/character/${character.id}`}>
                            <h3>{character.name}</h3>
                        </Link>
                        <Image
                            src={character.image}
                            alt={character.id.toString()}
                            width={200}
                            height={100}
                            loader={ImageLoader}
                            unoptimized
                        ></Image>
                    </div>
                );
            })}
            <HelloPage />
        </>
        // </div>
    );
}

export const getStaticProps: GetStaticProps = async (context) => {
    console.log("holaaaaaaaaaaaaaaaaaaaaa");
    const res = await axios.get("http://rickandmortyapi.com/api/character");
    console.log(res);
    const { results }: GetCharacterResults = await res.data;
    console.log(results);
    return {
        props: { characters: results },
    };
};
// export const getServerSideProps = async () => {};
