import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import HelloPage from "./hello";
import axios from "axios";
import { GetStaticProps, NextPage } from "next";
import { GetCharacterResults } from "../types";

const inter = Inter({ subsets: ["latin"] });

// export const Home: NextPage = ({ characters }: any) => {
//     return (
//         <>
//             <Head>
//                 <title>Create Next App</title>
//                 <meta name="description" content="Generated by create next app" />
//                 <meta name="viewport" content="width=device-width, initial-scale=1" />
//                 <link rel="icon" href="/favicon.ico" />
//             </Head>
//             {JSON.stringify(characters)}
//             <HelloPage />
//         </>
//     );
// };
export default function Home({ characters }: any) {
    return (
        // <div className={styles.main}>
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {JSON.stringify(characters)}
            <HelloPage />
        </>
        // </div>
    );
}

export const getStaticProps: GetStaticProps = async (context) => {
    console.log("holaaaaaaaaaaaaaaaaaaaaa");
    const res = await axios.get("http://rickandmortyapi.com/api/character");
    console.log(res);
    const { results }: GetCharacterResults = await res.data;
    console.log(results);
    return {
        props: { characters: results },
    };
};
// export const getServerSideProps = async () => {};
